<?xml version='1.0' encoding='utf-8'?>
<algebra>
  <basicAlgebra>
    <algName>Test</algName>
    <cardinality>4</cardinality>
    <operations>
      <op>
        <opSymbol>
          <opName>d0</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">0,0,0,0</row>
            <row r="[1]">0,0,0,0</row>
	    <row r="[2]">0,0,0,0</row>
	    <row r="[3]">0,0,0,0</row>         
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>d1</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">1,1,1,1</row>
            <row r="[1]">1,1,1,1</row>
	    <row r="[2]">1,1,1,1</row>
	    <row r="[3]">1,1,1,1</row>            
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>d2</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">2,2,2,2</row>
            <row r="[1]">2,2,2,2</row>
	    <row r="[2]">2,2,2,2</row>
	    <row r="[3]">2,2,2,2</row>            
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>d3</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">3,3,3,3</row>
            <row r="[1]">3,3,3,3</row>
	    <row r="[2]">3,3,3,3</row>
	    <row r="[3]">3,3,3,3</row>            
          </intArray>
        </opTable>
      </op>
      <op>
        <opSymbol>
          <opName>d</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">0,1,2,3</row>
            <row r="[1]">1,2,3,0</row>
	    <row r="[2]">2,3,0,1</row>
	    <row r="[3]">3,0,1,2</row>            
          </intArray>
        </opTable>
      </op>
    </operations>
  </basicAlgebra>
</algebra>