<?xml version="1.0"?>
<algebra>
  <basicAlgebra>
    <algName>Z3</algName>
    <cardinality>3</cardinality>
    <operations>
      <op>
        <opSymbol>
          <opName>d</opName>
          <arity>2</arity>
        </opSymbol>
        <opTable>
          <intArray>
            <row r="[0]">0,1,2</row>
            <row r="[1]">1,2,0</row>
	    <row r="[2]">2,0,1</row>
          </intArray>
        </opTable>
      </op>
    </operations>
  </basicAlgebra>
</algebra>
